#!/bin/bash
set -ex -o pipefail

cd "$(dirname $0)"

cat > Marlin/PrintrBotConfig.h << ENDCONFIG
/** @jssjr's home printer config **/

#define ZROD_QUARTER 1
#define PULLEY_XY_16T 1
#define EXTRUDER_OLD 1
#define X_AXIS_UPGRADE 1
#define ZROD_STANDARD 1
ENDCONFIG

# Upgraded to E3D v6 hotend, uses Semitec 104GT2 based thermistor
# See: https://wiki.e3d-online.com/Temperature_Sensor_Documentation#Thermistor
sed -i '' -e 's/#define TEMP_SENSOR_0 1/#define TEMP_SENSOR_0 5/' Marlin/Configuration.h

pio run -e printrboard_revf
